### ISSUE TITLE
Laravel 10 support?

### ISSUE THREAD

**Issue by quyle92** [jn-jairo/laravel-ngrok#11]
I tried to use it with Larvel 10 but encountered this: `jn-jairo/laravel-ngrok v2.0.0 requires php ^7.3 -> your php version (8.1.16) does not satisfy that requirement.`

May I know when the new version with Laravel 10 support is released?

Thanks!

**Comment by jn-jairo** [comment]
I was working on a new test system when the Laravel 10 came out, that caused the delay on the Laravel 10 support.

Now the new release is available [v3.0.0](https://github.com/jn-jairo/laravel-ngrok/releases/tag/v3.0.0) with support to Laravel 10.
