### ISSUE TITLE
Support for new ngrok domains

### ISSUE THREAD

**Issue by jonaszkadziela** [jn-jairo/laravel-ngrok#12]
**Is your feature request related to a problem? Please describe.**
In [this blog post](https://ngrok.com/blog-post/new-ngrok-domains) from the 6th of April 2023, the Ngrok team announced that they will be rolling out new domains. Technically, the `ngrok.io` base domain is still available for old accounts, but not for free tier users as far as I can see.

Applications of free users will be served from these domains:
- `ngrok-free.app`
- `ngrok-free.dev`

While applications of paid users will be served from these:
- `ngrok.app`
- `ngrok.dev`

**Describe the solution you'd like**
I think the way of determining ngrok host in `NgrokServiceProvider` needs to be changed. Probably other parts of the codebase will also need to be adjusted.

**Describe alternatives you've considered**
I tried to force `ngrok.io` domain using `--hostname` option, but this feature is only available for paid users.

**Additional context**
![New domain](https://user-images.githubusercontent.com/34022120/231479937-c744a68d-62a4-40f2-8cf2-7a3a18089908.png)

![Custom hostname not allowed](https://user-images.githubusercontent.com/34022120/231479163-c27b1c62-a029-4115-bf22-b8c20a115230.png)

**Comment by jn-jairo** [comment]
New domains added, please update to the new release [v3.0.1](https://github.com/jn-jairo/laravel-ngrok/releases/tag/v3.0.1).
