### ISSUE TITLE
 ngrok: not found

### ISSUE THREAD

**Issue by tofariasti** [jn-jairo/laravel-ngrok#14]
- PHP Version: 8.2.5
- Laravel Framework Version: 10
- Ngrok Version: 3

**Describe the bug**
When write sail artisan ngrock the output: sh: 1: exec: ngrok: not found

**To Reproduce**
When write sail artisan ngrock the output: sh: 1: exec: ngrok: not found

**Expected behavior**

**Additional context**
![image](https://github.com/jn-jairo/laravel-ngrok/assets/131496768/375cd749-0041-4079-b25e-4e6ef495d9a8)

**Comment by jn-jairo** [comment]
Ngrok is a requirement, it must be available and accessible, make sure you installed ngrok properly and it is accessible from any path.
