### ISSUE TITLE
sh: 1: exec: ngrok: not found

### ISSUE THREAD

**Issue by odaiderawi** [jn-jairo/laravel-ngrok#5]
- Version: #.#.#
- PHP Version: 7.4
- Laravel Framework Version: 7.4
- Ngrok Version: 2

**Describe the bug**
when type php artisan ngrok i got this response "sh: 1: exec: ngrok: not found"

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context or screenshots about the problem here.

**Comment by jn-jairo** [comment]
It requires the ngrok command
