### ISSUE TITLE
PHP Version v8.0.8 Not Compatible For Laravel Framework Version v8.40

### ISSUE THREAD

**Issue by theWebKeyGuy** [jn-jairo/laravel-ngrok#6]
- Version: 2.0.0
- PHP Version: 8.0.8
- Laravel Framework Version: 8.40

**Describe the bug**
Having an issue with the PHP version not being supported states it only supports version ^7.3 the latest suggested version for Laravel 8.40 is 8.0.8. Can't use this plugin unless this issue is fixed.

**To Reproduce**
1. Install fresh laravel version.
2. install sail to get docker setup.
3. attempt to install plugin with "sail composer require --dev jn-jairo/laravel-ngrok"
4. See error in console about PHP version.

**Expected behavior**
Would expect it to work the newer versions of PHP.

**Comment by jn-jairo** [comment]
PHP 8 added please update to v2.0.1
